### ISSUE TITLE
Script crash

### ISSUE THREAD

**Issue by JamesDAdams** [da-pingwing/plex-tvtime-agent#1]
Hi, i try to test thos script on my pc but i have this error

C:\Users\JamesAdams\Downloads\plex-tvtime-agent-master>python main.py
[Plex-TvTime-Agent] Starting PLEX - TvTime automatic agent by Clovis Warlop
[Plex-TvTime-Agent] Based off: https://github.com/imrabti/tvshowtime-plex
[Plex-TvTime-Agent][Authentication] Token not found - Starting with token request
Expecting value: line 1 column 1 (char 0)
[Plex-TvTime-Agent][Authentication][Error] Issue in authentication

**Comment by da-pingwing** [comment]
TvTime has discontinued their API 
![image](https://user-images.githubusercontent.com/1765794/124562912-c43a0080-de69-11eb-9d40-56f63b879278.png)
